"""Publish only the owner-selected native1024 Dragonspine frame."""
import pathlib,json,hashlib
OUT=pathlib.Path(__file__).resolve().parent;ROUND3=OUT.parents[1]
paths=sorted(OUT.glob('*-metadata.json'));assert len(paths)==1
p=paths[0];m=json.loads(p.read_text());c=m['camera']
assert m['variant']=='shader-native' and m['size']==[1024,1024] and c['yaw']==-55 and c['fov']==60
checks=json.loads((OUT/'evidence/image-artifact-check.json').read_text())['frames'];assert len(checks)==1 and checks[0]['file']==m['file']
visual=json.loads((OUT/'evidence/artifact-review.json').read_text())['frames'];assert len(visual)==1 and visual[0]['file']==m['file']
framing=json.loads((OUT/'evidence/selected-framing-check.json').read_text());coverage=json.loads((OUT/'evidence/selected-native-coverage.json').read_text());assert framing['pass'] and coverage['pass']
coverage={**{k:coverage[k] for k in ('configuredNativeRenderDistanceChunks','checkedCacheRadiusChunks','requiredChunks','statuses','heightmapColumns','minimumSurfaceY','maximumSurfaceY','pass')},'sourceEmptyColumnCount':len(coverage['sourceEmptyColumns']),'sourceEmptyColumnsInInvisiblePadding':sum(r['strictlyBehindView'] and r['outsideConfigured32ChunkWindow'] for r in coverage['emptyColumnVisibility']),'unprovenOrVisibleSourceEmptyColumns':len(coverage['unprovenOrVisibleSourceEmptyColumns']),'evidence':'captures-teyvat/renders-dragonspine/evidence/selected-native-coverage.json'}
entry={'project':'GenshinInMinecraft','label':'Dragonspine — Complementary native — heading -55° — FOV 60°','path':m['file'],'method':'Actual Minecraft1.21.10/Fabric0.18.4; native1024×1024 F2 screenshot, first-person spectator, HUD hidden. No crop, retouching, compositing or output resampling.','source':m['source'],'notes':'Owner-selected composition recaptured at1024 square using the identical recorded camera, heading, shader profile, time and clear weather. Six static-landmark comparisons against the selected1280 reference verify framing. FOV60 is the nominal slider with flight FOV effects enabled; approximately66 effective, based on the earlier measured flight-FOV isolation. Complementary Reimagined5.7.1 LOW and native32 with BORDER_FOG=true; Iris present, DH absent. This is intentionally a summit/Nail detail with a fog-limited background, not whole-mountain long-range coverage. The central vertical beacon is legitimate map content. Fourteen alternatives were retired to round3/removed; prior15-frame evidence and exact author versions are preserved under evidence/history-15-frame-delivery/.','profile':m['variant'],'modsPresent':m['modsPresent'],'camera':c,'cameraCommandExecuted':m['cameraCommand'],'size':m['size'],'time':4000,'weather':'clear; daylight and weather cycles disabled','shaderPackInstalled':'ComplementaryReimagined_r5.7.1.zip','shaderPackEnabled':True,'sha256':m['sha256'],'metadata':str(p.relative_to(ROUND3)),'artifactCheck':checks[0],'visualReview':visual[0],'framingProof':framing,'nativeCoverageProof':coverage,'runtimeMetrics':m['runtimeMetrics'],'evidence':'captures-teyvat/renders-dragonspine/evidence/selected-framing-check.json'}
(OUT/'manifest.json').write_text(json.dumps([entry],indent=2))
scripts={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for pattern in ('*.py','*.sh','*.args') for p in sorted(OUT.glob(pattern))}
(OUT/'script-sha256.json').write_text(json.dumps(scripts,indent=2))
print(f'1 selected native1024 frame, {len(scripts)} saved author-script hashes')
