modLoader="javafml"
loaderVersion="[11,)"
license="MIT"
issueTrackerURL="https://github.com/brainage04/GenshinInMinecraft/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="brainage04"
description='''Recreates Genshin Impact gameplay in Minecraft on top of the WanggMC Blocky Teyvat map.'''
iconFile="assets/genshininminecraft/icon.png"
displayURL="https://github.com/brainage04/GenshinInMinecraft"

[[mixins]]
config="genshininminecraft.mixins.json"

[[mixins]]
config="genshininminecraft.client.mixins.json"

[[dependencies.genshininminecraft]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.genshininminecraft]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.genshininminecraft]]
modId="cloth_config"
type="required"
versionRange="[${cloth_config_version},)"
ordering="AFTER"
side="BOTH"
