modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="brainage04"
description='''My modern Minecraft Fabric modding template.'''
iconFile="assets/genshininminecraft/icon.png"

[[mixins]]
config="genshininminecraft.mixins.json"

[[mixins]]
config="genshininminecraft.client.mixins.json"

[[dependencies.genshininminecraft]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.genshininminecraft]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.genshininminecraft]]
modId="fzzy_config"
type="required"
versionRange="[0.7.6,)"
ordering="AFTER"
side="BOTH"
